### PR TITLE
Update binary name and paths

### PR DESCRIPTION
**Pull request by NikVolf**

### CODE REVIEW

**Comment by NikVolf** [comment]
I don't like pzcash, can't be spelled )

the other client is `zcashd`, so ours could be just `zcash`

Maybe also `zcp`, `zcashr` (rust)

**Comment by gavofyork** [comment]
`zc`?

**Comment by pepyakin** [comment]
`parity-zc`?

**Comment by NikVolf** [comment]
> `parity-zc`?

only one word, no dashes!

**Comment by folsen** [comment]
`python-zc` and `libzc` exists, otherwise i'm not particularly opinionated ^^

**Comment by NikVolf** [comment]
I like `pzc` also

**Comment by str4d** [comment]
If you wanted to match the existing binary-naming scheme it would be `pzec`.

**Comment by NikVolf** [comment]
> If you wanted to match the existing binary-naming scheme it would be `pzec`.

oh, and what scheme would that be? What is also named according this scheme?

**Comment by str4d** [comment]
pbtc, is it not?

**Comment by mineZcash** [comment]
Seems that `pbtc` is already established.  `pzec` makes sense. https://github.com/paritytech/parity-bitcoin/tree/master/pbtc

**Comment by bitzec** [comment]
pzc  vs  pzec

**Comment by NikVolf** [comment]
Ok, pzec indeed seems like the name which provides more info about the product behind

**Pull request merged**
