### PR TITLE
Update + read + verfiy sapling commitment tree where required

### LINKED ISSUE #3: Verification meta issue
Meta-issue to synchronize verification rules development. High-level list of what needs to be done + current status:
- [x] Block pre-verification (`verify_block.rs`): completed;
- [x] Header pre-verification (`verify_header.rs`): completed (with local equihash impl);
- [ ] Transaction pre-verification (`verify_transaction.rs`): completed, except for [zk-SNARKs verification](https://github.com/zcash/zcash/blob/master/src/main.cpp#L1076);
- [x] Block verification (`accept_block.rs`): in-progress, needs check, detailed list:
- - [x] finalized transactions;
- - [x] BIP34;
- - [x] founders reward.
- [x] Header verification (`accept_header.rs`): in-progress, needs check, detailed list:
- - [x] work required;
- - [x] timestamp;
- - [x] version.
- [ ] Transaction verification (`accept_transaction.rs`): in-progress, needs check, detailed list:
- - [x] version, version group if && flags checks;
- - [x] drop expired transactions;
- - [x] size limits;
- - [x] SignatureHash (probably take from `SegWit`?);
- - [ ] join split - related checks;
- - [ ] sapling - related checks;
- - [x] sigops checks;
- - [x] coinbase-related checks (maturity, protected, ...);
- - [x] script checks;
- - [x] money range checks;
- [x] check && disable/enable verification-related BIPs / ZIPs

### LINKED ISSUE #27: RPC methods meta issue
- [x] `BlockChain`:
- - [x] `getbestblockhash`;
- - [x] `getblockcount`;
- - [x] `getblockhash`;
- - [x] `getdifficulty` - currently returns difficulty of the best block. Should calculate difficulty for next block. TODO: check `pbtc`;
- - [x] `getblock` - update response with ZCash-specific fields;
- - [x] `gettxout` - check if we need non-transparent addresses for this;
- - [x] `gettxoutsetinfo` - not implemented in `pbtc`.
- [ ] `Miner`:
- - [ ] `getblocktemplate` - update with ZCash-specific fields (`finalsaplingroot`).
- [x] `Network`:
- - [x] `addnode`;
- - [x] `getaddednodeinfo`;
- - [x] `getconnectioncount`.
- [x] `Raw`:
- - [x] `sendrawtransaction`;
- - [x] `createrawtransaction` - update with ZCash-specific fields + addresses;
- - [x] `decoderawtransaction` - not implemented in `pbtc`.
- - [x] `getrawtransaction` - not implemented in `pbtc`.

### PR DESCRIPTION
**Pull request by svyatonik**
closes #27 

Could be reviewed commit-by-commit:
- [this one](https://github.com/paritytech/parity-zcash/commit/807822a9fdd56a15649183784f736222015656d5) - updates commitment tree when block is inserted into db;
- [this one](https://github.com/paritytech/parity-zcash/commit/bc85459e15213f80b23f09474c7e2ccbc96cc146) - introduces last (needs double check when we'll close #3) Sapling-related verification step - checks that `final_sapling_root` field of the block header matches computed;
- [this one](https://github.com/paritytech/parity-zcash/commit/0680e9835b922d1e50d14e6a0d5fc8529e04b22a) - reads Sapling commitment tree state when `getblocktemplate` RPC is executed.

There's a single quite important TODO left there - we do not need to save default (empty) commitment tree states until Sapling is really activated. This would either require `db` level to know about `ConsensusParams` or some other heuristic (probably - return default state if there's no state in db OR do not save state until non-default state is first met). I'll file a separate issue about that.

### CODE REVIEW

**Comment by NikVolf** [comment]
Sure we need separate columns for sprout/sapling trees?
Since the empty roots of of sapling and sprout trees are different, they have zero chance to overlap being in one column

**Comment by svyatonik** [comment]
I don't have a strong opinion on this :) Do you think it is better to use single column?

**Comment by NikVolf** [comment]
> I don't have a strong opinion on this :) Do you think it is better to use single column?

I think we'd better avoid unneeded complexity :)

**Comment by NikVolf** [comment]
Same for block roots?
headers are have unique hash

**Comment by svyatonik** [comment]
There are sapling && sprout root for every block.

**Comment by svyatonik** [comment]
Just realized that the root of Sapling tree is stored in the block header (`final_sapling_root`) - so I'll make a PR to remove `COL_SAPLING_BLOCK_ROOTS`.

**Pull request merged**
